### PR TITLE
Update antlr4 dependency version from 4.7.2 to 4.13.0; update CI scripts to always build with Java 11 but still targeting and testing Java 8

### PR DESCRIPTION
**Pull request by kohlschuetter**
This fixes a "unused import" warning in target/generated-sources.

### CODE REVIEW

**Comment by kohlschuetter** [comment]
This is blocked on the CI builds still running with Java 8.

Antlr [changed their internal code](https://github.com/antlr/antlr4/releases/tag/4.10) to be Java 11+ only, even though the produced code still compiles for source/target version 8.

Do we still need to run the v8 builds? Can we change them so they're building with Java 11 but run on Java 8?

**Comment by msangel** [comment]
Java 8 is still ~ 30% usage so that’s why it stick with antlr3. Let’s keeping it until usage of it will be much lower.
IMG_2300

**Comment by msangel** [comment]
Oh, sorry. So we can compile j11, but have it running on 8? Cool. And what’s are benefits of antlr 4 for this project? It simply works well!

**Comment by kohlschuetter** [comment]
We already use antlr4 exclusively; they just bumped the build requirements to Java 11 at some point.

**Pull request merged**
