### PR TITLE
Add Maven Wrapper

### PR DESCRIPTION
**Pull request by jvanzyl**

### CODE REVIEW

**Comment by jvanzyl** [comment]
@bkiers is it ok to merge this? I still have access for making releases, but happy to help with infra related work as well. I'm going to try and finally release my Jekyll implementation so just updating things and master is failing so I wanted to add the Maven Wrapper and some basic GitHub Actions. This is the first step.

**Review by bkiers — APPROVED** [review]
:+1:

**Comment by bkiers** [comment]
> @bkiers is it ok to merge this?

Yes, will merge, thanks!

> I still have access for making releases, but happy to help with infra related work as well. I'm going to try and finally release my Jekyll implementation so just updating things and master is failing so I wanted to add the Maven Wrapper and some basic GitHub Actions. This is the first step.

:+1: 

Feel free to publish a new (`0.8.0`) release to Maven.

**Comment by jvanzyl** [comment]
You guys just let me know, happy to publish to Maven Central whenever you wish. I see an 8 alpha there already, so just let me know what you want to do.

**Comment by jvanzyl** [comment]
Also if you have a preferred chat app, happy to chat there. I have no strong opinion. Slack, Zulip, Discord. Just not Teams :-)

**Comment by msangel** [comment]
@jvanzyl hello.
Yes, I made a draft there, but due to issues with keys I was unable to finish the flow. It wold be nice to have publishing as GitHub action for simplifying the release. Thanks!

**Comment by jvanzyl** [comment]
I can work on GitHub Actions, first for building and testing (master seems to have an issue for me here locally) and later for performing releases.

**Pull request merged**
